# -*- coding: utf-8 -*-
"""streamfinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MOyD6gj7-Ly7Zt33MXmhD6g_Nizg6I9a
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="Income & Work Analysis Dashboard",
    layout="wide"
)

# ---------------- TITLE ----------------
st.title("Income & Work Analysis Dashboard")

st.markdown("""
This interactive dashboard explores income and work patterns using demographic and employment data.

Use the filter on the left to compare telework and non-telework employees and explore how income and efficiency change.
""")

# ---------------- LOAD DATA ----------------
df = pd.read_csv("IPUMS.csv")

# ---------------- CLEAN DATA ----------------
df['TELWRKPAY'] = df['TELWRKPAY'].fillna(0)
df = df[df['INCWAGE'] < 99999999]
df = df[df['WKSWORK1'] > 0]
df = df[(df['UHRSWORKT'] > 0) & (df['UHRSWORKT'] < 997)]

# ---------------- FEATURE ENGINEERING ----------------
df['HourlyEfficiency'] = df['INCWAGE'] / (df['WKSWORK1'] * df['UHRSWORKT'])

# ---------------- SIDEBAR FILTER ----------------
st.sidebar.header("Filters")

telework_option = st.sidebar.selectbox(
    "Telework Status",
    [0, 1],
    format_func=lambda x: "No Telework Pay" if x == 0 else "Receives Telework Pay"
)

df = df[df['TELWRKPAY'] == telework_option]

# ---------------- KPI METRICS ----------------
st.subheader(" Key Insights")

col1, col2, col3 = st.columns(3)

col1.metric("Total Observations", len(df))
col2.metric("Average Income", f"${df['INCWAGE'].mean():,.0f}")
col3.metric("Avg Hourly Efficiency", f"{df['HourlyEfficiency'].mean():.2f}")

st.divider()

# ---------------- VISUALIZATIONS ----------------
col1, col2 = st.columns(2)

# -------- PLOT 1 --------
with col1:
    st.markdown("### Average Income by Age")

    income_age = df.groupby("AGE")["INCWAGE"].mean().reset_index()

    fig1 = px.line(
        income_age,
        x="AGE",
        y="INCWAGE",
        title="Income Trends by Age"
    )

    st.plotly_chart(fig1, use_container_width=True)

# -------- PLOT 2 --------
with col2:
    st.markdown("### Hourly Efficiency Distribution")

    fig2 = px.histogram(
        df,
        x="HourlyEfficiency",
        nbins=30,
        title="Distribution of Work Efficiency"
    )

    st.plotly_chart(fig2, use_container_width=True)

st.divider()

# ---------------- SUMMARY ----------------
with st.expander(" View Summary Statistics"):
    st.write(f"Number of observations: {len(df)}")
    st.write(f"Average income: ${df['INCWAGE'].mean():,.2f}")
    st.write(f"Average hourly efficiency: {df['HourlyEfficiency'].mean():.2f}")
    
