# -*- coding: utf-8 -*-
"""streamfinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MOyD6gj7-Ly7Zt33MXmhD6g_Nizg6I9a
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import plotly.express as px

st.title("Income and Work Analysis")

df = pd.read_csv("IPUMS.csv")

df['TELWRKPAY'] = df['TELWRKPAY'].fillna(0)

df = df[df['INCWAGE'] < 99999999]
df = df[df['WKSWORK1'] > 0]
df = df[(df['UHRSWORKT'] > 0) & (df['UHRSWORKT'] < 997)]

df['HourlyEfficiency'] = df['INCWAGE'] / (df['WKSWORK1'] * df['UHRSWORKT'])

telework_option = st.selectbox("Telework Pay (0 = No, 1 = Yes)", [0, 1])

df = df[df['TELWRKPAY'] == telework_option]

st.subheader("Average Income by Age")

income_age = df.groupby("AGE")["INCWAGE"].mean().reset_index()

fig1 = px.line(income_age, x="AGE", y="INCWAGE")
st.plotly_chart(fig1)

st.subheader("Hourly Efficiency Distribution")

fig2 = px.histogram(df, x="HourlyEfficiency", nbins=30)
st.plotly_chart(fig2)

st.write("Number of rows:", df.shape[0])
st.write("Average income:", round(df["INCWAGE"].mean(), 2))