# -*- coding: utf-8 -*-
"""streamfinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MOyD6gj7-Ly7Zt33MXmhD6g_Nizg6I9a
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import os

st.title("Income Analysis Dashboard")

file_path = "/content/IPUMS.csv"

if not os.path.exists(file_path):
    st.error("IPUMS.csv not found. Make sure it is in /content/")
    st.stop()

ipums_df = pd.read_csv(file_path)

x_var = st.selectbox("X axis", ["AGE", "EDUC", "UHRSWORKT"])

st.subheader("Income vs Selected Variable")

fig = px.scatter(ipums_df, x=x_var, y="INCWAGE")
st.plotly_chart(fig)
